#!/usr/bin/env python3
"""Regenerate docs/cards/index.md -- a gallery table of every challenge
card, grouped by track, linking to each card's rendered front/back/sheet.

Usage:
    python3 generate_card_index.py --cards-dir /path/to/docs/cards
"""
import argparse
from pathlib import Path

import yaml

TRACK_ORDER = ["beginner", "intermediate", "advanced"]
TRACK_LABEL = {"beginner": "Beginner (Green)", "intermediate": "Intermediate (Blue)", "advanced": "Advanced (Black)"}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cards-dir", required=True)
    args = parser.parse_args()

    cards_dir = Path(args.cards_dir).resolve()
    cards = []
    for card_yaml in sorted(cards_dir.glob("*/card.yaml")):
        with open(card_yaml) as f:
            cards.append(yaml.safe_load(f))

    lines = [
        "# Challenge Cards",
        "",
        "Print-ready challenge cards generated by the `challenge-card` skill. "
        "Each card is a single 8.5x11 sheet: print one-sided, fold in half, laminate.",
        "",
    ]

    for track in TRACK_ORDER:
        track_cards = [c for c in cards if c.get("track") == track]
        if not track_cards:
            continue
        lines.append(f"## {TRACK_LABEL[track]}")
        lines.append("")
        lines.append("| Card | Chapter | Status | Front / Back | Print Sheet |")
        lines.append("|---|---|---|---|---|")
        for c in track_cards:
            cid = c["card_id"]
            lines.append(
                f"| {c['title']} | {c.get('chapter', '')} | {c.get('status', '')} "
                f"| [Front]({cid}/front.html) / [Back]({cid}/back.html) "
                f"| [sheet.pdf]({cid}/sheet.pdf) |"
            )
        lines.append("")

    (cards_dir / "index.md").write_text("\n".join(lines))
    print(f"wrote {cards_dir / 'index.md'} ({len(cards)} cards)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
