#!/usr/bin/env python3
"""Regenerate docs/cards/TODO.md -- a checklist of challenge cards that
have a detailed image-prompt.md ready but no illustration yet, so an
agent with image-generation tools knows exactly what to pick up next.

A card counts as "pending" when its card.yaml has no front.icon_image
set AND an image-prompt.md file exists next to it. A card whose front-
side authoring step forgot to write image-prompt.md is reported as a
warning instead (it needs Step 1b of the challenge-card skill, not an
image), so it never gets silently skipped.

Usage:
    python3 update_image_todo.py --cards-dir /path/to/docs/cards
"""
import argparse
import sys
from pathlib import Path

import yaml


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cards-dir", required=True)
    args = parser.parse_args()

    cards_dir = Path(args.cards_dir).resolve()
    pending = []
    missing_prompt = []

    for card_yaml in sorted(cards_dir.glob("*/card.yaml")):
        with open(card_yaml) as f:
            card = yaml.safe_load(f)
        card_dir = card_yaml.parent
        has_image = bool((card.get("front", {}) or {}).get("icon_image"))
        prompt_path = card_dir / "image-prompt.md"
        if has_image:
            continue
        if prompt_path.exists():
            pending.append((card["card_id"], card["title"], f"{card_dir.name}/image-prompt.md"))
        else:
            missing_prompt.append((card["card_id"], card["title"]))

    lines = [
        "# Challenge Card Image Generation TODO",
        "",
        "Auto-generated by `scripts/update_image_todo.py` -- do not hand-edit, it will",
        "be overwritten. Cards below have a detailed image prompt ready but no",
        "illustration yet.",
        "",
        "## For the image-generation agent",
        "",
        "For each pending card:",
        "",
        "1. Read the linked `image-prompt.md` and generate the illustration it",
        "   describes.",
        "2. Save the PNG into that same card directory (e.g.",
        "   `docs/cards/<card-id>/<card-id>.png`).",
        "3. Set `front.icon_image` (the PNG filename) and `front.icon_image_alt`",
        "   (a short plain-language description) in that card's `card.yaml`.",
        "4. Re-render the card: `python3 skills/challenge-card/scripts/",
        "   render_card_pdf.py --card-dir docs/cards/<card-id>`.",
        "5. Re-run this script so the card drops off the list below.",
        "",
        "## Pending",
        "",
    ]

    if pending:
        for card_id, title, prompt_rel in pending:
            lines.append(f"- [ ] **{title}** (`{card_id}`) -- prompt: `{prompt_rel}`")
    else:
        lines.append("None right now -- every card either has an illustration or no prompt yet.")
    lines.append("")

    if missing_prompt:
        lines.append("## Missing image-prompt.md (authoring incomplete)")
        lines.append("")
        lines.append(
            "These cards have no `front.icon_image` and no `image-prompt.md` either -- "
            "Step 1b of the challenge-card skill was skipped. Author the prompt before "
            "adding these to the image-generation queue."
        )
        lines.append("")
        for card_id, title in missing_prompt:
            lines.append(f"- **{title}** (`{card_id}`)")
        lines.append("")

    (cards_dir / "TODO.md").write_text("\n".join(lines))
    print(f"wrote {cards_dir / 'TODO.md'} ({len(pending)} pending, {len(missing_prompt)} missing prompt)")
    if missing_prompt:
        print("WARNING: some cards are missing image-prompt.md -- see TODO.md", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
